Repository autrainer/autrainer, pull requests merged in 2024-12, with the labels that each got.

#73 Fix openSMILE Feature Extraction Transform Output Shape
  autrainer/transforms/specific_transforms.py
  tests/test_transforms.py
Labels: bug

#54 Update dataset interface
  autrainer/core/scripts/preprocess_script.py
  autrainer/datasets/abstract_dataset.py
  autrainer/datasets/aibo.py
  autrainer/datasets/dcase_2016_t1.py
  autrainer/datasets/dcase_2018_t3.py
  autrainer/datasets/dcase_2020_t1a.py
  autrainer/datasets/edansa2019.py
  autrainer/datasets/emo_db.py
  autrainer/datasets/speech_commands.py
  autrainer/datasets/utils/dataset_wrapper.py
  autrainer/training/training.py
  docs/source/modules/transforms.rst
  tests/test_datasets.py
  tests/test_preprocessing.py
Labels: feature, improvement

#76 Add Missing Trainer Type Annotations and Docstrings
  autrainer/training/training.py
  autrainer/training/utils.py
  docs/source/modules/training.rst
Labels: improvement

#77 Fix Multi-Target Regression Typo and Add Missing MTR Tests
  autrainer/datasets/abstract_dataset.py
  tests/test_datasets.py
Labels: bug, improvement

#78 Fix Order of Batch Size and Inference Batch Size Dataset Arguments
  autrainer/datasets/abstract_dataset.py
  autrainer/datasets/aibo.py
  autrainer/datasets/dcase_2016_t1.py
  autrainer/datasets/dcase_2018_t3.py
  autrainer/datasets/dcase_2020_t1a.py
  autrainer/datasets/edansa2019.py
  autrainer/datasets/emo_db.py
  autrainer/datasets/speech_commands.py
Labels: bug

#80 Fix Dataset Dataframe Inconsistencies
  autrainer/datasets/abstract_dataset.py
  autrainer/datasets/aibo.py
  autrainer/datasets/dcase_2016_t1.py
  autrainer/datasets/dcase_2018_t3.py
  autrainer/datasets/dcase_2020_t1a.py
  autrainer/datasets/emo_db.py
  autrainer/datasets/toy_dataset.py
  autrainer/training/training.py
  docs/source/examples/tutorials/esc_50.py
  docs/source/modules/datasets.rst
  docs/source/usage/tutorials.rst
  tests/test_datasets.py
Labels: improvement

#83 Remove Deprecated Get Evaluation Data Method
  autrainer/datasets/abstract_dataset.py
Labels: bug

#85 Fix Per-Example Loss and Refactor Outputs Tracker
  autrainer/core/wrappers/instantiate.py
  autrainer/criterions/criterion_wrappers.py
  autrainer/optimizers/sam.py
  autrainer/training/outputs_tracker.py
  autrainer/training/training.py
  docs/source/examples/optimizer_custom_step.py
  docs/source/examples/tutorials/random_scaled_sgd.py
  docs/source/modules/criterions.rst
  docs/source/modules/optimizers.rst
  docs/source/usage/tutorials.rst
  tests/test_criterions.py
Labels: bug, improvement
