Repository autrainer/autrainer, pull requests merged in 2025-01, with the labels that each got.

#87 Speed up Trainer Initialization
  autrainer/core/scripts/preprocess_script.py
  autrainer/core/utils/__init__.py
  autrainer/core/utils/bookkeeping.py
  autrainer/core/utils/hardware.py
  autrainer/core/utils/requirements.py
  autrainer/training/training.py
  tests/test_core_utils.py
Labels: improvement

#94 Fix Undefined Features Path in Preprocessing Script
  autrainer/core/scripts/preprocess_script.py
Labels: bug

#79 Support Remote Code for Hugging Face Inference
  autrainer/core/scripts/inference_script.py
  autrainer/serving/model_paths.py
Labels: improvement

#95 Fix ToyDataset Initialization Order
  autrainer/datasets/toy_dataset.py
Labels: bug

#96 Fix Device Fallback if not Compiled with Cuda
  autrainer/core/utils/hardware.py
Labels: bug

#99 Fix Unescaped Tilde Character in Plotting Tutorial Docs
  docs/source/usage/tutorials.rst
Labels: bug, docs

#97 Remove Checkpoint Attributes from Model Config during Fetching
  autrainer/core/scripts/fetch_script.py
Labels: bug
