Repository autrainer/autrainer, pull requests merged in 2025-04, with the labels that each got.

#122 Add AudioSet Dataset
  autrainer-configurations/dataset/AudioSet-wav.yaml
  autrainer/datasets/__init__.py
  autrainer/datasets/audioset.py
  docs/source/modules/datasets.rst
  poetry.lock
  pyproject.toml
Labels: feature

#132 Fix Mutable Hydra Multirun Configurations
  autrainer-configurations/_autrainer_.yaml
  autrainer-configurations/config.yaml
  autrainer-configurations/hydra/callbacks/ConfigDirSnapshot.yaml
  autrainer/core/scripts/fetch_script.py
  autrainer/core/scripts/group_script.py
  autrainer/core/scripts/preprocess_script.py
  autrainer/core/scripts/train_script.py
  autrainer/core/scripts/utils.py
  autrainer/core/utils/hardware.py
  autrainer/core/wrappers/config_dir_snapshot.py
  autrainer/core/wrappers/main.py
Labels: bug

#138 SED: Update CRNN model
  autrainer/models/crnn.py
Labels: feature, improvement

#141 Automatically Increment Generator Seed in Augmentation Pipeline
  autrainer/augmentations/augmentation_pipeline.py
  tests/test_augmentations.py
Labels: improvement
