Repository autrainer/autrainer, pull requests merged in 2025-03, with the labels that each got.

#82 Add Support for Global Transforms
  autrainer/core/scripts/preprocess_script.py
  autrainer/datasets/abstract_dataset.py
  autrainer/datasets/aibo.py
  autrainer/datasets/toy_dataset.py
  autrainer/training/training.py
  autrainer/transforms/__init__.py
  autrainer/transforms/smart_compose.py
  autrainer/transforms/specific_transforms.py
  autrainer/transforms/transform_manager.py
  docs/source/modules/transforms.rst
  tests/test_datasets.py
  tests/test_preprocessing.py
  tests/test_transforms.py
Labels: improvement

#61 Overhaul data pipeline using structs
  autrainer/augmentations/image_augmentations.py
  autrainer/core/scripts/preprocess_script.py
  autrainer/datasets/abstract_dataset.py
  autrainer/datasets/toy_dataset.py
  autrainer/datasets/utils/__init__.py
  autrainer/datasets/utils/data_struct.py
  autrainer/datasets/utils/dataset_wrapper.py
  autrainer/models/abstract_model.py
  autrainer/models/ast_model.py
  autrainer/models/cnn_10.py
  autrainer/models/cnn_14.py
  autrainer/models/end2you.py
  autrainer/models/ffnn.py
  autrainer/models/leaf.py
  autrainer/models/sequential.py
  autrainer/models/tdnn.py
  autrainer/models/timm_wrapper.py
  autrainer/models/torchvision_wrapper.py
  autrainer/models/utils.py
  autrainer/models/whisper.py
  autrainer/optimizers/sam.py
  autrainer/training/training.py
  autrainer/transforms/smart_compose.py
  autrainer/transforms/specific_transforms.py
  docs/source/examples/augmentation_get_collate_fn.py
  docs/source/examples/optimizer_custom_step.py
  docs/source/examples/tutorials/MultiBranchData-C.yaml
  docs/source/examples/tutorials/MultiBranchModel.yaml
  docs/source/examples/tutorials/multi_branch_data.py
  docs/source/examples/tutorials/multi_branch_model.py
  docs/source/examples/tutorials/random_scaled_sgd.py
  docs/source/modules/augmentations.rst
  docs/source/modules/dataset_utils.rst
  docs/source/modules/models.rst
  docs/source/modules/optimizers.rst
  docs/source/usage/tutorials.rst
  tests/test_augmentations.py
  tests/test_datasets.py
  tests/test_models.py
  tests/test_optimizers.py
  tests/test_preprocessing.py
  tests/test_transforms.py
Labels: improvement

#114 Fix Redundant Disaggregated Evaluation Calculation
  autrainer/training/training.py
Labels: bug

#115 Dynamically Resolve Global Standardizer Position
  autrainer/transforms/specific_transforms.py
  tests/test_transforms.py
Labels: improvement

#46 Add MSP-Podcast dataset
  autrainer-configurations/dataset/MSPPodcast-EmoAct-wav.yaml
  autrainer-configurations/dataset/MSPPodcast-EmoClass-all-wav.yaml
  autrainer-configurations/dataset/MSPPodcast-EmoClass-big4-wav.yaml
  autrainer-configurations/dataset/MSPPodcast-EmoDom-wav.yaml
  autrainer-configurations/dataset/MSPPodcast-EmoVal-wav.yaml
  autrainer/datasets/__init__.py
  autrainer/datasets/msppodcast.py
  docs/source/modules/datasets.rst
  tests/test_datasets.py
Labels: feature

#126 Fix too Small Dev and Test Loss Average during Tracking
  autrainer/training/training.py
Labels: bug
